# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

Pool:'ubuntu-latest'

pr:'none'

stages:
  - stage:
    jobs:
      - job: 'build'
        steps:
          -script: 'dotnet build'

  - stage:
    jobs:
      - job: 'test'
        dependOn: 'build'
        steps:
          - script: 'dotnet test'

  - stage:
    jobs:
      - job: 'publish'
        dependOn: 'test'
        steps:
          -script: 'dotnet publish'

name:'$(date:yyyyMMdd)$(rev:rr)'